### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by stevemarple** [python-zwoasi/python-zwoasi#15]
I no longer have access to a ZWO camera and so cannot test the examples for Python module. I've included all of the outstanding pull requests (thanks @asgaut, @JochenBroz, @matt-phair and @jamienoss), updated the contributors file (`AUTHORS.rst`)  and released a final, untested 0.1.0 release. 

If anyone is willing to be the new maintainer for this project please comment below.

**Comment by iromero91** [comment]
I use this library every day with my ASI178MM (only that model) and I plan to keep it working, I think I could take that over.

**Comment by jamienoss** [comment]
Hi, sorry for the delay I have been out on leave.

I too have access and am happy to help out here.

**Comment by iromero91** [comment]
@stevemarple Still willing to take over. Using this library currently at work. I already got a couple of PRs lined up.

**Comment by iromero91** [comment]
Pinging again. I still actively use this library and have been maintaining it in my fork.

**Comment by stevemarple** [comment]
Unless I hear any objections or alternative suggestions I think I should transfer the python-zwoasi repository to @iromero91, following instructions described at https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

If anyone thinks I should create a team and transfer to that instead then please shout now, and suggest who should be members.

I'm CC'ing @AndreEbel, @cinbody, @hollanderic, @m4tt-willi4ms, and @sergachev for input as they all have forked python-zwoasi, have made commits to their local branch, and were not previously mentioned in this issue. Apologies if I missed anyone.

I'm going to give everyone one week to make suggestions or comment. If I don't hear objections I'll transfer on 2021-06-20 or as soon as reasonable afterwards.

@iromero91 Are you happy with that?

**Comment by cinbody** [comment]
Sounds good, I really haven't done anything with it since that early work.
Thanks for keeping it alive.

**Comment by iromero91** [comment]
@stevemarple Sounds good to me. Unless somebody else wants to take active maintenance with me to justify an org I'd be happy to manage the repo in my personal space.

**Comment by sergachev** [comment]
> Unless I hear any objections or alternative suggestions I think I should transfer the python-zwoasi repository to @iromero91, following instructions described at https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository
> 
> If anyone thinks I should create a team and transfer to that instead then please shout now, and suggest who should be members.
> 
> I'm CC'ing @AndreEbel, @cinbody, @hollanderic, @m4tt-willi4ms, and @sergachev for input as they all have forked python-zwoasi, have made commits to their local branch, and were not previously mentioned in this issue. Apologies if I missed anyone.
> 
> I'm going to give everyone one week to make suggestions or comment. If I don't hear objections I'll transfer on 2021-06-20 or as soon as reasonable afterwards.
> 
> @iromero91 Are you happy with that?

Hey!

First of all - thank you for the library, it works well for a while now.
For me your proposal is fine. I use it continuously at work so will be able to test changes if necessary.

Ilia


Ilia

**Comment by AndreEbel** [comment]
Hi all ! 

I am glad this repo gets a new active maintainer. I totally approve this move.

André

**Comment by AstroKeith** [comment]
Fine by me too. Great work all round.
Keith

**Comment by stevemarple** [comment]
Tried to transfer yesterday evening but failed with error `iromero91/python-zwoasi already exists`. Notified @iromero91 by email. Awaiting response on best way to proceed.

**Comment by stevemarple** [comment]
Thank you to everyone who has contributed to this project. I have now transferred the repository to the [python-zwoasi](https://github.com/python-zwoasi) organisation. Many thanks @iromero91 for becoming the new maintainer.

The new home for `python-zwoasi` is now https://github.com/python-zwoasi/python-zwoasi Links to my original repository should get redirected however to avoid confusion please update any local repository remotes with `git remote`. For more information see

- https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#whats-transferred-with-a-repository
- https://docs.github.com/en/get-started/getting-started-with-git/managing-remote-repositories

Steve
