### ISSUE TITLE
Getting better than 8-bit color with python-zwoasi

### ISSUE THREAD

**Issue by t-ara-fan** [python-zwoasi/python-zwoasi#19]
Hi Steve,

I downloaded python-zwoasi and it worked right away. It is easy to use and the examples are great. Thanks.

I want to get 12-bit color images from my ASI224MC camera.  It seems that the SDK and thus your examples offer RGB24 (8 bits per color using ASI_IMG_RGB24) and RAW16 (monochrome using ASI_IMG_RAW16).  ZWO has made comments that 8-bit color is sufficient but I don't think so.

Have you looked at getting RGB with 16-bit (so 12-bits of real data fits in) color through the SDK?  

SharpCap offers RAW16 image capture which shows as color when showing "Video" in the SharpCap.  A snapshot saves a .png files that at first glance is monochrome. But once debayered with PixInsight it is a color image.  However I can't tell so far if the color image is 12-bit saved in 16-bit format, or if it is still just 8-bit. 

My ZWO ASI071MC Pro definitely gives 14-bit color with programs like SequenceGeneratorPro and N.I.N.A. so I am not sure if the small color cameras are limited, or one needs to know more about the SDK to get higher bit depth. 

Your insight is appreciated.

**Comment by iromero91** [comment]
I haven't looked too carefully but those applications may be doing their own demosaicing.  the RAW16 images are not monochrome, they are the raw data from the bayer filters, if saved in the correct format you could then open them in something like darktable to develop them properly.

**Comment by t-ara-fan** [comment]
Thanks. I will try that.

**Comment by iromero91** [comment]
I'm closing this for now. If there are further issues feel free to reopen the issue.
