### ISSUE TITLE
New pypi release

### ISSUE THREAD

**Issue by iromero91** [python-zwoasi/python-zwoasi#23]
Looks like the last release made to the python package index was 4 years ago. @stevemarple could you give me a hand getting set up to make a new release? I do believe I need to have an API key on pypi to be able to upload a new release.

**Comment by stevemarple** [comment]
Sure, I'd forgotten about pypi. I need your pypi username so that I can include you as a project collaborator.

**Comment by iromero91** [comment]
@stevemarple username is iromero91. Thanks.

**Comment by iromero91** [comment]
Pushed the state of the pre-maintainer switch release to pypi. I will be preparing another release later with my changes.
