### ISSUE TITLE
Problem with zwoasi

### ISSUE THREAD

**Issue by easybob95** [python-zwoasi/python-zwoasi#8]
Hello,
i would like to control my asi178mc with a raspberry pi 3 b+.

I have already wrote a program to test the raspberry with the picamera v2 and it works great, except the fact IMX219 is not a suitable sensor for astro. I used python language and common libraries like poencv, numpy, PIL, tkinter.

I have tried to install your python biding for asi sdk. The command pip install zwoasi seems to work fine.

When i try to run your zwoasi_demo.py program, it says "Import Error : no module named 'zwoasi'.

I can't find any solution.

I have also downloaded zwo SDK but i must say i don't know what to do with it.

I suppose you have understand i am complete newbie with linux and raspberry.

Could you explain me step by step :
- what i must do with zwo sdk
- how i can import zwoasi

What i would expect is to be able to import asi commands in python program as i import for example numpy in a python program and start to develop a software for the asi178mc.

Many thanks in advance for your lights !

Alain

**Comment by kanoalani** [comment]
They both need to be found by the python interpreter. 

For a python library ask the python interpreter to tell you where it searches for packages and copy the zwoasi directory to one of them.

For the zwoasi package to find the SDK library, give it the full path - either the environment variable ZWO_ASI_LIB or coding the path in your script or in your configuration method. Look at one of the included example programs to get ideas. To find the path to the library you will need to know which ARM architecture you have -  whatever the 'uname' command says, like armv7 or armv6

**Comment by iromero91** [comment]
I don't believe this is an issue anymore. please feel free to reopen if there are further questions. If you install the SDK in the standard library paths, #17 simplifies this greatly.
